### ISSUE TITLE
Ruby Errors

### ISSUE THREAD

**Issue by jstirzaker** [pauly/lightwaverf#11]
Liking what you have developed, although not got it working yet. I've recently acquired the newer 930 wifi link running 2.91Y firmware with a 2-gang dimmer.

I'm trying to control this from a raspberry pi with your code but hit ruby errors for basically each command. Got around a few of them, but getting settings from the server is an issue, complaining about certificate not being verified. Any ideas?

Any plans for more development on this project?

**Comment by theredprince** [comment]
I've also just got hold of the 930 wifi link specifically to use it with this Ruby gem :)

Whilst I can download the settings from the server using the 'update' command it doesn't seem to be operating the on/off socket that I'm testing with.

I don't get any errors though.

It's all working ok from the iOS app and the website too.

Would be great to get this going, just not sure if it's compatible with the newer wifi link?

**Comment by theredprince** [comment]
I'm not sure if this is anything useful but thought I'd document just in case.

When using lightwaverf's website I can see it sends the following command string:

!R1D1F1|Office|lamp On

This works as expected. Tailing the command line, when a command is sent it reports this:

666,!R1D1F1|Turn Office lamp|F1

Which doesn't work - is the differing structure an issue or is this just logging formatting?

**Comment by theredprince** [comment]
Also, it's always 666 at the start - is this supposed to increment with each command?

**Comment by hxpaul** [comment]
Hi thanks for the feedback, hasn't been an update for a while I know, apologies!
The number at the start of the instruction `666` has always worked for me, it doesn't seem to matter what the number is.
If you're setting up for the first time try `lightwaverf initlink` - at some point you had to start sending an initialising message to the wifi link.

**Comment by hxpaul** [comment]
@jstirzaker i'd have to see this working, could be they've changed how you connect to their servers. I don't use their servers at all I just maintain my own config but I'll give this a try later.

**Comment by theredprince** [comment]
hey @hxpaul 

thanks so much for the reply.

I just ran 'lightwave initlink' and recieved the following:

'666,ERR,2,"Not yet registered. See LightwaveLink"'

I guess that's the issue - not sure on how to resolve this though, any ideas?

**Comment by hxpaul** [comment]
try again and look at the led display on your link as you do this, and it'll flash up "do you want to pair with this device" or similar
hope the new links still have the same display and work in the same way...

**Comment by theredprince** [comment]
Yes! That was it, it's working now.

The new links don't have a display but instead have one button and a LED status light.

After running `lightwaverf initlink` I checked the link and the LED was flashing green so I clicked the button and resent a command and it's all working.

Can't wait to get stuck into it now, thanks again!

**Comment by hxpaul** [comment]
nice one!
Not sure how much more dev work i'll do, I've had too many hardware failures with the lightwaverf double sockets so when I have the money I'll be trying out some other solutions.

**Comment by theredprince** [comment]
Yeah, they are not the most robust hardware are they, I've had three units fail so far.

It's a real shame as their offering is quite comprehensive, say compared to belkin and phillips who produce better hardware just not the range of products, and of course being quite pricey too.

I'll keep an eye on your blog to see how you get on!

**Comment by hxpaul** [comment]
I love the form of the sockets, they're nice looking than any others imo and the price is good. But the relays in them just seem to fail, I've had three where one side has failed too.
Thanks for the feedback anyway, I really appreciate it.

**Comment by jstirzaker** [comment]
Thanks for your feedback, I'll take a look at this as well.  But with regards to my original problem, please see the error below, now that i've had a chance to rerun it, any ideas:

$ lightwaverf update jstirzaker@email.com 0000
/usr/lib/ruby/1.9.1/net/http.rb:799:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from /usr/lib/ruby/1.9.1/net/http.rb:799:in `block in connect'
        from /usr/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
        from /usr/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
        from /usr/lib/ruby/1.9.1/net/http.rb:799:in `connect'
        from /usr/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
        from /usr/lib/ruby/1.9.1/net/http.rb:744:in `start'
        from /usr/lib/ruby/1.9.1/net/http.rb:1284:in `request'
        from /usr/lib/ruby/1.9.1/net/http.rb:1307:in `send_entity'
        from /usr/lib/ruby/1.9.1/net/http.rb:1096:in `post'
        from /var/lib/gems/1.9.1/gems/lightwaverf-0.7/lib/lightwaverf.rb:225:in `update_config'
        from /var/lib/gems/1.9.1/gems/lightwaverf-0.7/bin/lightwaverf:30:in `<top (required)>'
        from /usr/local/bin/lightwaverf:23:in `load'
        from /usr/local/bin/lightwaverf:23:in `<main>'

**Comment by pauly** [comment]
looks like a problem with the certificate on the lightwaverf server to me,
rather than a problem with the gem, I will try it out with my own
credentials asap

**Comment by pauly** [comment]
I get the same error... when I go to
https://lightwaverfhost.co.uk/manager/index.php in the browser I get this
warning:

*Your connection to lightwaverfhost.co.uk <http://lightwaverfhost.co.uk> is
encrypted using an obsolete cipher suite. Further, this page includes other
resources which are not secure. These resources can be viewed by others
while in transit, and can be modified by an attacker to change the look of
the page.*

*The connection uses TLS 1.0.*

*The connection is encrypted using AES_256_CBC, with HMAC-SHA1 for message
authentication and DHE_RSA as the key exchange mechanism.*

We might not be able to use *lightwaverf update* until this is fixed. In
the menatime you can set up your rooms and devices with *lightwaverf
configure*

**Comment by jstirzaker** [comment]
Ok. Thanks for checking this out! Any workarounds? As was hoping to use it to generate a config file, or can I obtain from the server manually?

**Comment by hxpaul** [comment]
how many rooms and devices do you have? the config file is not complex, you can write it by hand or you can do

`lightwaverf configure`

and enter the rooms and devices in the same order you have them now

**Comment by hxpaul** [comment]
This page https://gist.github.com/mislav/5026283 offers a workaround...

**Comment by hxpaul** [comment]
also an updated version of ruby might do it

**Comment by jstirzaker** [comment]
Thanks for this I've tried to update the certs, but didn't seem to have much luck, must be an RPi thing. RPi comes with Ruby 1.9.3p194, from 2012, haven't figured out how to upgrade it yet to v2. Any ideas?

Good news though, managed to get it talking to the hub and can control my lights via the command line and with the script using a manually created config file.

**Comment by pauly** [comment]
@jstirzaker fixed this one in the new version. You can turn off certificate verification, which I have done.
