### ISSUE TITLE
'No implicit conversion of nil into String (Type Error)' 

### ISSUE THREAD

**Issue by theredprince** [pauly/lightwaverf#15]
Hi @hxpaul,

Just setting up a new installing this time on a RaspberryPi :+1:

All setup and config fine but I'm getting an error when running a command e.g. 

`lightwaverf bedroom light on`

The error message is referencing line 428 and is: 

`'No implicit conversion of nil into String (Type Error)' `

Also references line 36. I would copy the full error but not fully operational on the RaspberryPi yet so not easy! 

Do you think this has anything to do with the last change i.e. `add quotes in the room names that have spaces.`

Thanks a lot,
Dave

**Comment by pauly** [comment]
I'll take a look asap

**Comment by hxpaul** [comment]
Not sure what that line number refers to, it seems to be a blank line, can you update to the latest version please `gem install lightwaverf` and try again and if you still get the error email your config file too

**Comment by theredprince** [comment]
Sorry Paul, I noted down the wrong line, it's actually 428  

`if File.exist?( pythonFile )`

So the full error makes sense now:

`'exist?' :  No implicit conversion of nil into String (Type Error)`

Hope that's more helpful, sorry again!

I updated the gem but still receiving the error, will send through config if the above isn't any use.

Dave

**Comment by hxpaul** [comment]
I hope I fixed that at lunch, can you reinstall please and see if you're ok now?

**Comment by theredprince** [comment]
Reinstalled and message no longer appearing :+1: 

The commands don't appear to be operating the devices but probably not related to this issue. I'm going to retest on another computer incase it's an issue with the raspberry pi - will keep you posted.

Thanks a lot, appreciate it.

Dave

**Comment by hxpaul** [comment]
remember you have to pair the pi, or whichever computer you use, do `lightwaverf firmware` and then check the display on your wifi link

**Comment by theredprince** [comment]
Hi Paul,

I ran lightwaverf initlink first and have run lightwaverf firmware since,
are they the same? The link flashed and I pushed the pairing button so they
should be paired...?

**Comment by theredprince** [comment]
I have a suspicion this is something to with lightwaverf changing their iOS app perhaps? There's no longer a 'save settings to server' in the new app and I cannot add additional devices in the old app.

That said, I manually added a new socket to the config file and attempted to pair but no joy. Might just have to wait until the new web manager is released perhaps unless you have any other ideas?

Thanks,
Dave

**Comment by pauly** [comment]
I don't use the ios app or the server, this code only uses the config file,
so your room must be in there. You can download wht you have saved on the
lightwaverfhost server (the one I assume the app still uses) with
`lightwaverf update` but if your new room is not on their servers then it
won't get added to the config file that this uses... if you have done
`lightwaverf firmware` (could even do `lightwaverf firmware debug` and send
me the details) then all should be ok.

**Comment by theredprince** [comment]
Hi Paul, 

I think we're in action now. I tested on another machine which worked so I knew the general setup was fine, so tried again on the Pi and re-registered with the link and tested on a fresh socket. It looks like the sockets that aren't working have probably maxed out the 6 limit memory.

Thanks again for your help, ticket closed :)

Dave

**Comment by pauly** [comment]
Nice!
I just ordered some cheap lightwaverf sockets off eBay and they only support 3 pairings! Think they're old models. Still, they're cheap.
Glad your issue is fixed. You can clear the memory of your sockets completely.
Closing this one then.
