### ISSUE TITLE
Lightwaverf UDP commands stopped working after WIFI link update to version U2.90N

### ISSUE THREAD

**Issue by azewiusz** [pauly/lightwaverf#9]
Hi There,

I noticed that my PI lights service is not working any more. I realized that UDP commands are no longer recognized by WIFI link.

Can you tell me if the direct communication with LightwaveRF WIFI link still works for some of you ?

It appears that recently there was an update of WIFI Link firmware (I got U2.90N)

I see the latest LW Androind app still works.

**Comment by jamieburchell** [comment]
The registration command changed to `001,!F*p`

**Comment by weeksp** [comment]
I had problems with UDP commands after the 2.01 upgrade and it stopped me collecting and logging power measurements.  I found that the WiFi link now sends broadcast messages to 255.255.255.255.  More detail is on my blog:
http://pdwhomeautomation.blogspot.com/2015/02/fixing-lightwaverf-udp-power.html

Cheers
Paul

**Comment by pauly** [comment]
Calling `lightwaverf firmware` fixes these issues
